#!/usr/bin/env node
/**
 * Compliance scan.
 *
 * Lists every file:line in the codebase that carries a legal / clinical /
 * content placeholder so they can be reviewed in one pass before launch, and
 * fails on phrases that must never appear anywhere.
 *
 *   node scripts/compliance-scan.mjs                # print report
 *   node scripts/compliance-scan.mjs --strict       # exit 1 if any marker remains (launch gate)
 *   node scripts/compliance-scan.mjs --update-notes # rewrite the generated block in COMPLIANCE_NOTES.md
 *
 * Forbidden phrases always exit 1.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = process.cwd();
const args = new Set(process.argv.slice(2));
const strict = args.has("--strict");
const updateNotes = args.has("--update-notes");

/** Markers that must be resolved before launch, with what each one means. */
export const MARKERS = [
  ["CLAIM_PENDING_LEGAL_REVIEW", "Dosing specifics, mg amounts, or comparative claims. Counsel + clinical lead must approve wording."],
  ["TESTIMONIAL_PLACEHOLDER", "Deliberately ugly stand-in for social proof. Replace with approved testimonials or remove."],
  ["NOT FOR LAUNCH", "Content that must not ship."],
  ["PHARMACY_NAME_PLACEHOLDER", "Insert the dispensing pharmacy's legal name. Soha is never the dispensing pharmacy."],
  ["PRICING_PLACEHOLDER", "Pricing is not finalized. Values live only in the pricing config."],
  ["LEGAL_PLACEHOLDER", "Disclaimer / disclosure wording pending legal review."],
  ["COPY_DRAFT", "Copy written by the developer, not supplied in the brief. Needs brand + legal sign-off."],
  ["IMAGE_PLACEHOLDER", "Solid block standing in for brand photography. Swap for real imagery with alt text."],
];

/**
 * Phrases that must never appear in the codebase, in any casing / spacing /
 * hyphenation (ASCII or Unicode dashes). Add entries as { label, re }.
 *
 * History: the original brief barred "OB/GYN prescribed" and "bioidentical".
 * The client lifted both restrictions on 2026-09-05, so the list is empty.
 * Both remain factual claims (who prescribes / what the formulation is), so
 * wherever either is used it must sit next to a CLAIM_PENDING_LEGAL_REVIEW
 * marker. Example entry, kept for reference:
 *   { label: '"OB/GYN prescribed"',
 *     re: /ob\s*[\/\-\u2010-\u2015]?\s*gyn\s*[\-\u2010-\u2015]?\s*prescribed/i }
 */
export const FORBIDDEN = [];

const SKIP_DIRS = new Set(["node_modules", ".next", ".git", "out", "build", "screenshots"]);
const EXT = [".ts", ".tsx", ".js", ".mjs", ".md", ".mdx", ".json", ".css", ".svg"];
const SELF = new Set(["scripts/compliance-scan.mjs", "COMPLIANCE_NOTES.md"]);

function* walk(dir) {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) yield* walk(full);
    else if (EXT.some((e) => name.endsWith(e))) yield full;
  }
}

const hits = [];
const violations = [];
for (const file of walk(root)) {
  const rel = relative(root, file);
  if (SELF.has(rel)) continue;
  const lines = readFileSync(file, "utf8").split("\n");
  lines.forEach((line, i) => {
    for (const [marker] of MARKERS) {
      if (line.includes(marker)) hits.push({ file: rel, line: i + 1, marker, text: line.trim() });
    }
    for (const f of FORBIDDEN) {
      if (f.re.test(line)) violations.push({ file: rel, line: i + 1, label: f.label, text: line.trim() });
    }
  });
}

// ---- report ---------------------------------------------------------------

if (violations.length) {
  console.error("FORBIDDEN PHRASES FOUND — these must never appear anywhere in the codebase:");
  for (const v of violations) console.error(`  ${v.file}:${v.line}  ${v.label}  ${v.text}`);
  console.error("");
}

const byMarker = new Map();
for (const h of hits) byMarker.set(h.marker, [...(byMarker.get(h.marker) ?? []), h]);

console.log(`${hits.length} placeholder marker(s) found${hits.length ? ":" : "."}`);
for (const [marker, list] of byMarker) {
  console.log(`\n${marker} (${list.length})`);
  for (const h of list) console.log(`  ${h.file}:${h.line}`);
}

// ---- optional: refresh COMPLIANCE_NOTES.md ---------------------------------

if (updateNotes) {
  const notesPath = join(root, "COMPLIANCE_NOTES.md");
  const BEGIN = "<!-- BEGIN GENERATED: node scripts/compliance-scan.mjs --update-notes -->";
  const END = "<!-- END GENERATED -->";
  const esc = (s) => s.replace(/\|/g, "\\|").replace(/`/g, "'");
  let block = `${BEGIN}\n\n_Generated by \`node scripts/compliance-scan.mjs --update-notes\`. Do not edit by hand; re-run the script._\n\n`;
  block += `**Forbidden phrases:** ${violations.length === 0 ? "none found ✅" : `**${violations.length} FOUND ❌**`}\n\n`;
  block += `**Open placeholder markers:** ${hits.length}\n`;
  for (const [marker, meaning] of MARKERS) {
    const list = byMarker.get(marker) ?? [];
    block += `\n### \`${marker}\` — ${list.length}\n\n${meaning}\n\n`;
    if (!list.length) {
      block += "_None in codebase._\n";
      continue;
    }
    block += "| File | Line | Context |\n| --- | ---: | --- |\n";
    for (const h of list) block += `| \`${h.file}\` | ${h.line} | ${esc(h.text.slice(0, 110))}${h.text.length > 110 ? "…" : ""} |\n`;
  }
  block += `\n${END}`;
  const current = readFileSync(notesPath, "utf8");
  const start = current.indexOf(BEGIN);
  const end = current.indexOf(END);
  if (start === -1 || end === -1) {
    console.error("\nCOMPLIANCE_NOTES.md is missing the GENERATED markers; not updated.");
    process.exit(2);
  }
  writeFileSync(notesPath, current.slice(0, start) + block + current.slice(end + END.length));
  console.log("\nCOMPLIANCE_NOTES.md updated.");
}

if (violations.length || (strict && hits.length)) process.exit(1);
