#!/usr/bin/env node
/**
 * Lists every <Unverified> claim on the landing page, in page order, by
 * reading the rendered HTML — so the checklist in UNVERIFIED.md cannot drift
 * from what the page actually shows.
 *
 *   node scripts/unverified-list.mjs                          # print the list (needs `npm run dev` on :3000, or a build)
 *   node scripts/unverified-list.mjs --update                 # rewrite the generated block in UNVERIFIED.md
 *   node scripts/unverified-list.mjs --url http://host/path   # read from a running server instead of the build output
 *
 * Source, in order of preference: --url; the prerendered page in
 * .next/server/app (after `ALLOW_UNVERIFIED=1 npm run build`); the dev server.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const update = args.includes("--update");
const urlIndex = args.indexOf("--url");
const url = urlIndex === -1 ? null : args[urlIndex + 1];

const PAGE = "combination-cream";
const BUILT = join(root, ".next", "server", "app", `${PAGE}.html`);
const DEV_URL = `http://localhost:3000/${PAGE}`;

async function loadHtml() {
  if (url) return { html: await (await fetch(url)).text(), from: url };
  if (existsSync(BUILT)) return { html: readFileSync(BUILT, "utf8"), from: ".next/server/app (build output)" };
  try {
    return { html: await (await fetch(DEV_URL)).text(), from: DEV_URL };
  } catch {
    console.error(`Nothing to read: pass --url, run \`npm run dev\`, or build with ALLOW_UNVERIFIED=1 first.`);
    process.exit(2);
  }
}

const decode = (s) =>
  s
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();

/** Nearest preceding section id, so the list can be grouped. */
function sectionAt(html, index) {
  const before = html.slice(0, index);
  const matches = [...before.matchAll(/<section[^>]*\sid="([^"]+)"/g)];
  return matches.length ? matches[matches.length - 1][1] : "hero";
}

const { html, from } = await loadHtml();
const re = /<mark[^>]*data-unverified="([^"]*)"[^>]*>([\s\S]*?)<\/mark>/g;
const items = [];
for (const match of html.matchAll(re)) {
  items.push({ section: sectionAt(html, match.index), note: decode(match[1]), text: decode(match[2]) });
}

if (!items.length) {
  console.error(`No <Unverified> marks found (read from ${from}). Is the page rendering with highlights?`);
  process.exit(1);
}

const bySection = new Map();
for (const item of items) bySection.set(item.section, [...(bySection.get(item.section) ?? []), item]);

console.log(`${items.length} unverified claim(s) on /${PAGE} (read from ${from})\n`);
for (const [section, list] of bySection) {
  console.log(`#${section} (${list.length})`);
  for (const item of list) console.log(`  - [${item.note}] "${item.text}"`);
}

if (update) {
  const path = join(root, "UNVERIFIED.md");
  const BEGIN = "<!-- BEGIN GENERATED: node scripts/unverified-list.mjs --update -->";
  const END = "<!-- END GENERATED -->";
  const esc = (s) => s.replace(/\|/g, "\\|");
  let block = `${BEGIN}\n\n_Generated by \`node scripts/unverified-list.mjs --update\` from the rendered page. Do not edit by hand; re-run the script._\n\n`;
  block += `**Unverified claims on the page:** ${items.length}\n`;
  for (const [section, list] of bySection) {
    block += `\n### \`#${section}\` — ${list.length}\n\n| Done | Needs verifying | Placeholder currently shown |\n| :-: | --- | --- |\n`;
    for (const item of list) block += `| ☐ | ${esc(item.note)} | ${esc(item.text)} |\n`;
  }
  block += `\n${END}`;
  const current = readFileSync(path, "utf8");
  const start = current.indexOf(BEGIN);
  const end = current.indexOf(END);
  if (start === -1 || end === -1) {
    console.error("\nUNVERIFIED.md is missing the GENERATED markers; not updated.");
    process.exit(2);
  }
  writeFileSync(path, current.slice(0, start) + block + current.slice(end + END.length));
  console.log("\nUNVERIFIED.md updated.");
}
